---
apiVersion: v1
kind: Service
metadata:
  name: replication-postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  type: NodePort
  selector:
    app: postgres
