services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM=claim-qL1XRBjzPGB8v2_sKgGh
    volumes:
      - /home/bruno/plex/config:/config
      - /nvme0p2/media/tvshows:/tvshows
      - /nvme0p2/media/movies:/movies
    restart: unless-stopped

