version: '3'

services:
    docker-registry:
        platform: linux/arm64
        container_name: docker-registry
        image: registry:2
        ports:
            - 5000:5000
        restart: always
        volumes:
            - ./volumes:/var/lib/registry
        networks:
            - registry_network
    docker-registry-ui:
        platform: linux/arm64
        container_name: docker-registry-ui
        image: joxit/docker-registry-ui:main
        ports:
            - 8080:80
        environment:
            ENV_DOCKER_REGISTRY_HOST: docker-registry
            ENV_DOCKER_REGISTRY_PORT: 5000
        networks:
            - registry_network

networks:
    registry_network:
        driver: bridge
