apiVersion: apps/v1
kind: Deployment
metadata:
  name: { { RUNNER_NAME } }
  labels:
    app: { { RUNNER_NAME } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: { { RUNNER_NAME } }
  template:
    metadata:
      labels:
        app: { { RUNNER_NAME } }
    spec:
      containers:
        - name: runner
          image: docker.io/brunosienkiewicz420/projects:github-runner
          imagePullPolicy: Always
          env:
            - name: GITHUB_OWNER
              valueFrom:
                secretKeyRef:
                  name: { { SECRET_NAME } }
                  key: GITHUB_OWNER
            - name: GITHUB_REPOSITORY
              valueFrom:
                secretKeyRef:
                  name: { { SECRET_NAME } }
                  key: GITHUB_REPOSITORY
            - name: GITHUB_PERSONAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: { { SECRET_NAME } }
                  key: GITHUB_PERSONAL_TOKEN
            - name: DOCKER_HOST
              value: tcp://localhost:2375
          volumeMounts:
            - name: data
              mountPath: /work/
        - name: dind
          image: docker:24.0.6-dind
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          resources:
            requests:
              cpu: 20m
              memory: 512Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-graph-storage
              mountPath: /var/lib/docker
            - name: data
              mountPath: /work/
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: docker-graph-storage
          emptyDir: {}
        - name: data
          emptyDir: {}
